logging:
  level:
    root: info
    com.fastcampus.indexer: debug

spring:
  application:
    name: indexer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: password
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.names:fullJob}