version: '2.2'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fastcampus-es-elasticsearch
    container_name: es-node
    environment:
      - cluster.name=es-docker-cluster
      - node.name=fastcampus-es
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - IPC_LOCK
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      ELASTICSEARCH_URL: http://es-node:9200
      ELASTICSEARCH_HOSTS: http://es-node:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - es-net

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  es-net:
    driver: bridge
